### ISSUE TITLE
Any plans to support Apple silicon devices like M1 Macs?

### ISSUE THREAD

**Issue by davidxia** [tensorflow/tfx-bsl#48]
Is it possible to install tfx-bsl on M1 Macs either through pre-built distributions or from source? If not, are there any plans to support?

using M1 Mac, OS X 12.1, Python 3.8.12

```
pip install tfx-bsl
ERROR: Could not find a version that satisfies the requirement tfx-bsl (from versions: none)
ERROR: No matching distribution found for tfx-bsl
```

[I tried to build from source like so](https://gist.github.com/davidxia/468dadb7ffcb0e1c4a28947bcff0482c) but wasn't successful.

**Comment by yarri-oss** [comment]
To clarify for the rest of users following this, we are working to resolve macOS issues and working with the community to address errors when building `tfx-bsl` from source on Apple Silicon M1 Macs

**Comment by richardimms** [comment]
Even with the [new updates](https://github.com/tensorflow/tfx-bsl/commit/c60fb04aa63d953bd58ab219a463b8d47036ba93) to have the minimum version (11.0) and architecture to match arm64 I'm still facing the same issue.

**Comment by richardimms** [comment]
Wondering if there is any update on this as I still face the same issue.

**Comment by elia-secchi** [comment]
I can see there was a commit to include M1 macs, is this supporting arm64 architecture? I am unable to build the image on my side as I get blocked by the company firewall.

**Comment by iindyk** [comment]
> I can see there was a commit to include M1 macs, is this supporting arm64 architecture?

Could you please link the commit you are referring to?

> Are M1 Macs supported? Any plans to do so?

The support hasn't been tested on our side. There's a centralized effort in TFX to support M1 Macs which would also require support in tfx-bsl, but priority of this is not yet clear to me.

**Comment by elia-secchi** [comment]
> Could you please link the commit you are referring to?


Sure, this is the [commit](https://github.com/tensorflow/tfx-bsl/commit/c60fb04aa63d953bd58ab219a463b8d47036ba93)

**Comment by dvaldivia** [comment]
attempting to build master still fails  with

```
➜ python3 setup.py -q bdist_wheel
/opt/homebrew/lib/python3.9/site-packages/setuptools/dist.py:531: UserWarning: Normalizing '1.10.0.dev' to '1.10.0.dev0'
  warnings.warn(tmpl.format(**locals()))
2022/07/18 19:01:31 Downloading https://releases.bazel.build/5.2.0/release/bazel-5.2.0-darwin-arm64...
2022/07/18 19:01:31 Skipping basic authentication for releases.bazel.build because no credentials found in /Users/dvaldivia/.netrc
Extracting Bazel installation...
Starting local Bazel server and connecting to it...
INFO: Reading rc options for 'run' from /Users/dvaldivia/go/src/github.com/tensorflow/tfx-bsl/.bazelrc:
  Inherited 'build' options: --copt=-DTFX_BSL_USE_ARROW_C_ABI --cxxopt=-std=c++17 --incompatible_restrict_string_escapes=false --incompatible_require_linker_input_cc_api=false
ERROR: --incompatible_restrict_string_escapes=false :: Unrecognized option: --incompatible_restrict_string_escapes=false
Traceback (most recent call last):
```
`...`
```
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/opt/homebrew/bin/bazel', 'run', '-c', 'opt', '--macos_minimum_os=11.0', '--config=macos_arm64', '//tfx_bsl:move_generated_files']' returned non-zero exit status 2.
```

**Comment by dvaldivia** [comment]
same result for building inside the docker container

**Comment by JappaB** [comment]
I would exepect this to be solved for Tensorflow 2.10 (and it's compatible versions of sister libraries as mentioned here: https://github.com/tensorflow/tfx-bsl#compatible-versions). According to the blogpost, this should be the version that supports M1/aarch64. 

Am I wrong with this expectation?

**Comment by iindyk** [comment]
You're probably right with your expectation for TF, but not tfx_bsl. We cannot prioritize the support at the moment, but it is on our radar. We're trying to centralize the effort with other libraries and will update here once there's something to update with

**Comment by dvaldivia** [comment]
We are only asking for `tfx_bsl` support since everything depends on it, we cannot fix `tensorflow-io` until this is fixed for example

**Comment by JappaB** [comment]
Hi @iindyk,
Thanks for your answer! I understand that it might be hard to answer, but is there any (very rough) timeline you can give (even if it's just your gut feeling)? Should we think weeks, a couple months, a half year, a year, years...?

**Comment by jli** [comment]
@JappaB sai:
> I would exepect this to be solved for Tensorflow 2.10 (and it's compatible versions of sister libraries as mentioned here: https://github.com/tensorflow/tfx-bsl#compatible-versions). According to the blogpost: https://blog.tensorflow.org/2022/09/announcing-tensorflow-official-build-collaborators.html
> this should be the version that supports M1/aarch64.

But that blog post doesn't appear to mention Mac, M1/M2, or Apple Silicon - it seems to only be an update for "Windows Native and Linux Aarch64 hosts".

**Comment by oonisim** [comment]
If tfx-bsl does not work on Apple Silicon yet, please add the information. There are developers using Mac and Apple is moving to Apple Silicon, hence such clarity if a module works on Apple Silicon or not will prevent developers from getting in to installation issue and ending up with finding tfx-bsl does not work on Apple Silicon yet.

**Comment by Dentrax** [comment]
After hours of trying to install this package, finally hit this issue! It would be great to add the information in the README.

**Comment by Dentrax** [comment]
This is great @fatsmcgee! Would it work with Python 3.12 and Tensorflow 2.15.0?

**Comment by fatsmcgee** [comment]
> This is great @fatsmcgee! Would it work with Python 3.12 and Tensorflow 2.15.0?

Good question. I didn't test this myself, but I suspect that TF 2.15 would work, based on the fact that Tensorflow Transform reports its master branch [is tested against](https://github.com/tensorflow/transform#compatible-versions) tfx-bsl 0.14.0 and TF nightly (which should be at least as recent as TF 2.15). 

I don't think Python 3.12 is officially supported for Tensorflow 2.15, so you may have trouble there (e.g there are no wheels I know of that are compatible with 3.12).

**Comment by mihaimaruseac** [comment]
https://github.com/tensorflow/tensorflow/issues/62003 is the status for Python 3.12 support in TF

**Comment by tangm** [comment]
I did something similar to @fatsmcgee , but was able to build with just the avx exclusions. Have raised a pull request at https://github.com/tensorflow/tfx-bsl/pull/73 . Do you remember what errors you got wrt zetasql @fatsmcgee ?

**Comment by sid-kap** [comment]
@tangm I'm getting this zetasql error when I try `python setup.py bdist_wheel` on `master` on a Apple Silicon machine. I'm guessing it's the same as what @fatsmcgee got:
```/Users/sidharthkapur/clones/tfx-bsl/venv/lib/python3.9/site-packages/setuptools/dist.py:530: UserWarning: Normalizing '1.15.0.dev' to '1.15.0.dev0'
  warnings.warn(tmpl.format(**locals()))
running bdist_wheel
running build
running bazel_build
ERROR: /private/var/tmp/_bazel_sidharthkapur/ebc1df3f1b612a65a30d4b636202c7b7/external/com_google_zetasql/zetasql/parser/BUILD:26:8: @@com_google_zetasql//zetasql/parser:gen_extra_files: no such attribute 'exec_tools' in 'genrule' rule (did you mean 'executable'?)
ERROR: /private/var/tmp/_bazel_sidharthkapur/ebc1df3f1b612a65a30d4b636202c7b7/external/com_google_zetasql/zetasql/parser/BUILD:47:8: @@com_google_zetasql//zetasql/parser:gen_headers: no such attribute 'exec_tools' in 'genrule' rule (did you mean 'executable'?)
ERROR: /private/var/tmp/_bazel_sidharthkapur/ebc1df3f1b612a65a30d4b636202c7b7/external/com_google_zetasql/zetasql/parser/BUILD:57:8: @@com_google_zetasql//zetasql/parser:gen_protos: no such attribute 'exec_tools' in 'genrule' rule (did you mean 'executable'?)
ERROR: /private/var/tmp/_bazel_sidharthkapur/ebc1df3f1b612a65a30d4b636202c7b7/external/com_google_zetasql/zetasql/parser/BUILD:67:8: @@com_google_zetasql//zetasql/parser:gen_parse_tree_serializer_cc: no such attribute 'exec_tools' in 'genrule' rule (did you mean 'executable'?)
ERROR: /private/var/tmp/_bazel_sidharthkapur/ebc1df3f1b612a65a30d4b636202c7b7/external/com_google_zetasql/zetasql/parser/BUILD:77:8: @@com_google_zetasql//zetasql/parser:gen_parse_tree_serializer_headers: no such attribute 'exec_tools' in 'genrule' rule (did you mean 'executable'?)
WARNING: Download from https://mirror.bazel.build/github.com/tensorflow/tensorflow/archive/6887368d6d46223f460358323c4b76d61d1558a8.tar.gz failed: class java.io.FileNotFoundException GET returned 404 Not Found
INFO: Repository org_tensorflow_no_deps instantiated at:
  /Users/sidharthkapur/clones/tfx-bsl/WORKSPACE:93:13: in <toplevel>
Repository rule http_archive defined at:
  /private/var/tmp/_bazel_sidharthkapur/ebc1df3f1b612a65a30d4b636202c7b7/external/bazel_tools/tools/build_defs/repo/http.bzl:381:31: in <toplevel>
INFO: Repository icu instantiated at:
  /Users/sidharthkapur/clones/tfx-bsl/WORKSPACE:139:20: in <toplevel>
  /private/var/tmp/_bazel_sidharthkapur/ebc1df3f1b612a65a30d4b636202c7b7/external/com_google_zetasql/bazel/zetasql_deps_step_2.bzl:471:21: in zetasql_deps_step_2
Repository rule http_archive defined at:
  /private/var/tmp/_bazel_sidharthkapur/ebc1df3f1b612a65a30d4b636202c7b7/external/bazel_tools/tools/build_defs/repo/http.bzl:381:31: in <toplevel>
INFO: Repository markupsafe instantiated at:
  /Users/sidharthkapur/clones/tfx-bsl/WORKSPACE:139:20: in <toplevel>
  /private/var/tmp/_bazel_sidharthkapur/ebc1df3f1b612a65a30d4b636202c7b7/external/com_google_zetasql/bazel/zetasql_deps_step_2.bzl:367:25: in zetasql_deps_step_2
Repository rule http_archive defined at:
  /private/var/tmp/_bazel_sidharthkapur/ebc1df3f1b612a65a30d4b636202c7b7/external/bazel_tools/tools/build_defs/repo/http.bzl:381:31: in <toplevel>
INFO: Repository pybind11 instantiated at:
  /Users/sidharthkapur/clones/tfx-bsl/WORKSPACE:107:13: in <toplevel>
Repository rule http_archive defined at:
  /private/var/tmp/_bazel_sidharthkapur/ebc1df3f1b612a65a30d4b636202c7b7/external/bazel_tools/tools/build_defs/repo/http.bzl:381:31: in <toplevel>
INFO: Repository arrow instantiated at:
  /Users/sidharthkapur/clones/tfx-bsl/WORKSPACE:64:13: in <toplevel>
Repository rule http_archive defined at:
  /private/var/tmp/_bazel_sidharthkapur/ebc1df3f1b612a65a30d4b636202c7b7/external/bazel_tools/tools/build_defs/repo/http.bzl:381:31: in <toplevel>
ERROR: /private/var/tmp/_bazel_sidharthkapur/ebc1df3f1b612a65a30d4b636202c7b7/external/com_google_zetasql/zetasql/resolved_ast/BUILD:22:10: Target '@@com_google_zetasql//zetasql/parser:generator_utils' contains an error and its package is in error and referenced by '@@com_google_zetasql//zetasql/resolved_ast:gen_resolved_ast'
ERROR: Analysis of target '//tfx_bsl:move_generated_files' failed; build aborted: Analysis failed
INFO: Elapsed time: 0.779s, Critical Path: 0.00s
INFO: 1 process: 1 internal.
ERROR: Build did NOT complete successfully
ERROR: Build failed. Not running target
FAILED:
    Fetching repository @@bazel_tools~cc_configure_extension~local_config_cc; starting
    Fetching https://github.com/unicode-org/icu/releases/download/release-65-1/icu4c-65_1-src.tgz
    Fetching https://github.com/pallets/markupsafe/archive/2.1.1.tar.gz
Traceback (most recent call last):
  File "/Users/sidharthkapur/clones/tfx-bsl/setup.py", line 138, in <module>
    setup(
  File "/Users/sidharthkapur/clones/tfx-bsl/venv/lib/python3.9/site-packages/setuptools/__init__.py", line 87, in setup
    return distutils.core.setup(**attrs)
  File "/Users/sidharthkapur/clones/tfx-bsl/venv/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 185, in setup
    return run_commands(dist)
  File "/Users/sidharthkapur/clones/tfx-bsl/venv/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
    dist.run_commands()
  File "/Users/sidharthkapur/clones/tfx-bsl/venv/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 973, in run_commands
    self.run_command(cmd)
  File "/Users/sidharthkapur/clones/tfx-bsl/venv/lib/python3.9/site-packages/setuptools/dist.py", line 1217, in run_command
    super().run_command(command)
  File "/Users/sidharthkapur/clones/tfx-bsl/venv/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 992, in run_command
    cmd_obj.run()
  File "/Users/sidharthkapur/clones/tfx-bsl/venv/lib/python3.9/site-packages/wheel/bdist_wheel.py", line 299, in run
    self.run_command('build')
  File "/Users/sidharthkapur/clones/tfx-bsl/venv/lib/python3.9/site-packages/setuptools/_distutils/cmd.py", line 319, in run_command
    self.distribution.run_command(command)
  File "/Users/sidharthkapur/clones/tfx-bsl/venv/lib/python3.9/site-packages/setuptools/dist.py", line 1217, in run_command
    super().run_command(command)
  File "/Users/sidharthkapur/clones/tfx-bsl/venv/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 992, in run_command
    cmd_obj.run()
  File "/Users/sidharthkapur/clones/tfx-bsl/venv/lib/python3.9/site-packages/setuptools/_distutils/command/build.py", line 132, in run
    self.run_command(cmd_name)
  File "/Users/sidharthkapur/clones/tfx-bsl/venv/lib/python3.9/site-packages/setuptools/_distutils/cmd.py", line 319, in run_command
    self.distribution.run_command(command)
  File "/Users/sidharthkapur/clones/tfx-bsl/venv/lib/python3.9/site-packages/setuptools/dist.py", line 1217, in run_command
    super().run_command(command)
  File "/Users/sidharthkapur/clones/tfx-bsl/venv/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 992, in run_command
    cmd_obj.run()
  File "/Users/sidharthkapur/clones/tfx-bsl/setup.py", line 96, in run
    subprocess.check_call(
  File "/opt/homebrew/Cellar/python@3.9/3.9.18_2/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 373, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/opt/homebrew/bin/bazel', 'run', '-c', 'opt', '--macos_minimum_os=11.0', '--config=macos_arm64', '//tfx_bsl:move_generated_files']' returned non-zero exit status 1.
```
